apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  fluent.conf: |
    <source>
      @type tail
      format /^(?<time>\d.*?)\s+(?<action>\w+).\s+id=\"(?<id>.*?)\"\s+ip=\"(?<ip>.*?)\"\s+method=\"(?<method>.*?)\"\s+user=\"(?<user>.*?)\"\s+groups=(?<groups>.*?)\s+as=\"(?<as>.*?)\"\s+asgroups=\"(?<asgroups>.*?)\"\s+namespace=\"(?<namespace>.*?)\"\s+uri=\"(?<uri>.*?)\"$/
      path /var/log/kubernetes/kubernetes.audit
      pos_file /var/log/audit.pos
      time_format %Y-%m-%dT%H:%M:%S.%N%z
      tag audit.kubernetes
    </source>

    <match audit.kubernetes>
      @type elasticsearch
      host elasticsearch-fbiziumc-zs5x72
      port 9200
      logstash_format true
    </match>